name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: lint
        run: yarn lint
      - name: solhint
        run: yarn workspace contract solhint
      - name: format
        run: yarn prettier:check

  contract-test:
    runs-on: ubuntu-latest
    needs: check
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: Install truffle
        run: yarn global add truffle
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Run truffle node
        run: |
          cd packages/contract
          touch .secret
          truffle develop &
      - name: Test
        run: cd packages/contract && truffle test
      - name: Kill node
        run: kill $(lsof -t -i:9545)
